//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public int Id_klient { get; set; }
        public int Id_perfomance { get; set; }
        public System.DateTime Date_order { get; set; }
        public int Id_status { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Perfomance Perfomance { get; set; }
        public virtual Status_order Status_order { get; set; }
    }
}
